services:
  postgres:
    image: postgres:18.1-alpine
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=admin
      - PGDATA=/data/postgres
    ports:
      - 5432:5432
    volumes:
      - ../docker-volumes/postgres:/data/postgres
    restart: always
    networks:
      - go
  redis:
    image: redis:alpine
    ports:
      - 6379:6379
    volumes:
      - ../docker-volumes/redis:/data
    restart: always
    networks:
      - go
  mosquitto:
    image: eclipse-mosquitto:latest
    ports:
      - 1883:1883
    restart: always
    networks:
      - go
networks:
  go:
    name: go