services:
  postgres:
    image: postgres:18.1-alpine
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - PGDATA=/data/postgres
    ports:
      - ${POSTGRES_PORT}:5432
    volumes:
      - ../../docker-volumes/postgres:/data/postgres
    networks:
      - go
networks:
  go:
    name: go